---
apiVersion: v1
kind: Service
metadata:
  name: web-frontend
spec:
  type: NodePort
  selector:
      app: web-frontend
  ports:
    - port: {{ .Values.ingressPort }}
      protocol: TCP
      targetPort: 8080
---
# Environment variable method came from: https://javaadpatel.com/building-and-deploying-react-containers/
apiVersion: v1
kind: ConfigMap
metadata:
  name: web-config
data:
  web.properties: |
    window.REACT_APP_PROTOCOL= "{{ .Values.webProtocol }}"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-frontend
  labels:
    app: web-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: web-frontend
    spec:
      containers:
        - name: web-frontend
          # Change image name so it can be pulled from dockerHub more easily
          # Could also add a different directory root for dev vs prod using an environment variable
          # directory ./ vs ./grouphouse.io (or web-microservice-shell for now)
          # i.e. fictional.registry.example/imagename, `.` for dev, `dockerhub/...` for prod
          # TODO: need to replace with a per-project image
          image: docker.io/selleman/web-microservice-shell_web-frontend:latest
          imagePullPolicy: Always
          ports:
            - name: web-frontend
              containerPort: 8080
          volumeMounts:
            #override env-vars.js file to provide environment variables
            - name: config
              mountPath: "/usr/share/nginx/html/env-vars.js"
              subPath: "env-vars.js"
      volumes:
        - name: config
          configMap:
            name: web-config
            items:
              - key: "web.properties"
                path: "env-vars.js"
          # livenessProbe:
          #   httpGet:
          #    path: /
          #    port: 8080