# Ingress Port
ingressPort: 80

# Web Frontend
webProtocol: http
domain: localhost

# Public API
publicAPIPort: 8000 # NOTE: Must update this value manually in web-frontend/Dockerfile when changed
allowedOrigin: http://localhost

# GRPC
grpcName: grpc
grpcPort: 8001
grpcAddress: :8001

# API Store
psqlPort: 5432
psqlPortString: "'5432'" # k8s doesn't like integer environment variables :-(
psqlDriver: postgres
psqlUser: postgres-user
psqlPassword: secret # TODO: move to secrets
psqlName: postgresdb
psqlMigraterTableName: public-api
psqlMigrationPath: ./migrations
